### PR TITLE
Isolated Test Project

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
I've added a new test project in the root folder. The original repro app had too much unrelated code to isolate the NativeAd away form the unrelated code.

This demo project has a NativeAd in a UserControl (recommended instead of the approach you're using with event handlers in the model class). This way you have more control over the lifecycle of the ad and can properly manage resources (I saw your comment about the inevitable memory leak).

Open my demo and use your AdUnitId and AdAppId in MainViewModel and then run the app. You'll see that the ads in ItemTemplate will load, even if they fail to fetch the actual ad.

### CODE REVIEW

**Comment by LanceMcCarthy** [comment]
Quick follow up- 
You don't have to use your AdUnit ID to verify NativeAdV2 works in a GridView. You can just run it as-is and see my real ad units load.

image

**Comment by touseefbsb** [comment]
thanks for this @LanceMcCarthy . btw were you able to figure out what exactly was causing the bug? or is that still a mystery?

**Comment by LanceMcCarthy** [comment]
I didn't investigate the cause of the layout issue because honestly there was a lot of deprecated code and red herrings.

It was just faster to get to the bottom of the problem by staring over. 

If I were to guess, it's related to how the item is created and the parent layout. I don't think it's a coincidence that the ad image was at the top of the screen. 

Try to keep the ad object contained to the FrameworkElements of that User Control. And the data model can be responsible for the item in the view model (keep View and View Model separate)

**Comment by touseefbsb** [comment]
yeah that is what I was also suspecting, my approach was complicated, thankyou for the solution @LanceMcCarthy

**Pull request merged**
